### ISSUE TITLE
【 donut】padplus切换协议后room.findAll,出现的问题

### ISSUE THREAD

**Issue by ppBigGod** [wechaty/wechaty-puppet-hostie#111]
![image](https://user-images.githubusercontent.com/31261029/100330764-52175880-300a-11eb-873f-8258fa1147f9.png)
能不能解释为什么，并如何解决

**Comment by su-chang** [comment]
需要提供下更多的日志来确认问题。

通过目前日志来看，应该是在做当前请求时，wechaty服务端在重启。

建议在ready事件中执行此类操作。

**Comment by gaijinjoe** [comment]
> 需要提供下更多的日志来确认问题。
> 
> 通过目前日志来看，应该是在做当前请求时，wechaty服务端在重启。
> 
> 建议在ready事件中执行此类操作。

等了ready还是有同样的问题。以前在用padplus现在donut：

## 1. Versions
* What is your wechaty version? Answer: Tested with 0.51.10, 0.40.2 and 0.50.7 
* Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...) Answer: wechaty-puppet-hostie 
* What is your wechaty-puppet-XXX（padchat/puppeteer/） version? Answer:"puppeteer": "^2.1.1", 
* What is your node version? (run node --version) Answer: v12.14.1 
* What os are you using Answer: Mac 

## 2. Describe the bug
12:49:56 WARN Room findAll() room.ready() rejection:
Error: 13 INTERNAL: TIMEOUT, sync room member timeout, room id: 214032718@chatroom
    at Object.exports.createStatusError (/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/node_modules/grpc/src/client_interceptors.js:847:24)  The error is received each time there is a Contact.find({}) or Roam.find({}). 
     
## 3. To Reproduce
Try to find a contact within your contact list with something like bot.Contact.find({ id: “yourid” }) or bot.Room.find({ topic:”yourtopic”] })
