### ISSUE TITLE
 WARN Room findAll() room.ready() rejection: Error: 13 INTERNAL: TIMEOUT, sync room member timeout, room id: 18807422174@chatroom

### ISSUE THREAD

**Issue by ppBigGod** [wechaty/wechaty-puppet-hostie#113]
WARN Room findAll() room.ready() rejection:
Error: 13 INTERNAL: TIMEOUT, sync room member timeout, room id: 18807422174@chatroom
我该怎么解决这样的问题

**Comment by zhihuifanqiechaodan** [comment]
Meto , i need this question

**Comment by zhihuifanqiechaodan** [comment]
I also have this problem

**Comment by gaijinjoe** [comment]
same here. can't use ` bot.Contact.find() , bot.Contact.findAll() , bot.Room.find() , bot.Room.findAll()` any solution?

**Comment by huan** [comment]
What's [puppet service](https://wechaty.js.org/docs/puppet-services/) are you using when you have been experiencing this problem?

**Comment by gaijinjoe** [comment]
> What's [puppet service](https://wechaty.js.org/docs/puppet-services/) are you using when you have been experiencing this problem?

I've been using a `puppet_donut` key with `wechaty-puppet-hostie`. And I've been trying with wechaty 0.51.10, 0.40.2 and 0.50.7. I was using padplus before and it was working until it was deprecated.

**Comment by gaijinjoe** [comment]
> What's [puppet service](https://wechaty.js.org/docs/puppet-services/) are you using when you have been experiencing this problem?

1. Versions
* What is your wechaty version? Answer: Tested with 0.51.10, 0.40.2 and 0.50.7 
* Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...) Answer: wechaty-puppet-hostie 
* What is your wechaty-puppet-XXX（padchat/puppeteer/） version? Answer:"puppeteer": "^2.1.1", 
* What is your node version? (run node --version) Answer: v12.14.1 
* What os are you using Answer: Mac 

2. Describe the bug
12:49:56 WARN Room findAll() room.ready() rejection:
Error: 13 INTERNAL: TIMEOUT, sync room member timeout, room id: 214032718@chatroom
    at Object.exports.createStatusError (/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/node_modules/grpc/src/client_interceptors.js:847:24)  The error is received each time there is a Contact.find({}) or Roam.find({}). 
     
3. To Reproduce
Try to find a contact within your contact list with something like bot.Contact.find({ id: “yourid” }) or bot.Room.find({ topic:”yourtopic”] })
