### ISSUE TITLE
How does PadLocal operate as hostie service

### ISSUE THREAD

**Issue by Jesn** [wechaty/wechaty-puppet-hostie#119]
How does PadLocal operate as hostie service  ，and Multilingual wechaty access hostie service

**Comment by huan** [comment]
I have a blog post for this topic, please read https://wechaty.js.org/2021/01/14/wechaty-puppet-service/ and let me know if it helps.

**Comment by Jesn** [comment]
@huan  
my environment variables:

```
export WECHATY_PUPPET='wechaty-puppet-padlocal'
export WECHATY_PUPPET_PADLOCAL_TOKEN='my padlocal token'
export WECHATY_TOKEN='puppet_hostie_mytoken'
export WECHATY_HOSTIE_PORT=8788
export WECHATY_LOG="verbose"
```


```
Error:
puppet npm module not supported: "wechaty-puppet-padlocal"
learn more about supported Wechaty Puppet from our directory at
<https://github.com/wechaty/wechaty-puppet/wiki/Directory>

    at Function.resolveName (/wechaty/src/puppet-manager.ts:109:13)
    at Function.resolve (/wechaty/src/puppet-manager.ts:81:35)
    at Wechaty.initPuppet (/wechaty/src/wechaty.ts:397:48)
    at Wechaty.start (/wechaty/src/wechaty.ts:690:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at IoClient.start (/wechaty/src/io-client.ts:126:7)
07:44:58 ERR Wechaty start() exception:
puppet npm module not supported: "wechaty-puppet-padlocal"
```

**Comment by huan** [comment]
Please use `wechaty/wechaty:next` to support padlocal for now.

See: https://github.com/wechaty/wechaty/discussions/1985#discussioncomment-266563
