### ISSUE TITLE
Hostie will stop with some unknow reason.

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet-hostie#25]
11:39:43 VERB PuppetServiceImpl messageSendText()
11:39:43 VERB PuppetWindows messageSendText("17962906510@chatroom", dong)
11:39:43 VERB Donut(ffi-adapter) SendWeChatData(1,{"data":{"content":"dong","to_wxid":"17962906510@chatroom"},"type":11036})
11:39:43 VERB ffi-adapter Backend.lib(0: "C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dlls\WxLoader.dll")
11:39:43 VERB Bridge processEvent(RECV_TEXT_MSG)
11:39:43 VERB PuppetWindows onMessage({"at_user_list":[],"from_wxid":"wxid_4wkls7tu62ua12","is_pc":1,"msg":"dong","msgid":"7864579085001411733","room_wxid":"17962906510@chatroom","timestamp":1586403583,"to_wxid":"17962906510@chatroom","wx_type":1})
11:39:43 VERB PuppetWindows contactRawPayload(wxid_4wkls7tu62ua12)
11:39:43 VERB Bridge contactRawPayload(wxid_4wkls7tu62ua12)
11:39:43 VERB Message static load(7864579085001411733)
11:39:43 VERB Message constructor(7864579085001411733) for class Message
11:39:43 VERB Message ready()
11:39:43 VERB Puppet messagePayload(7864579085001411733)
11:39:43 VERB PuppetWindows messageRawPayload(7864579085001411733)
11:39:43 VERB Bridge messageRawPayload(7864579085001411733)
11:39:43 VERB EventStreamManager grpcEmit(EVENT_TYPE_MESSAGE[2], {"messageId":"7864579085001411733"})
11:39:43 VERB PuppetWindows messageRawPayloadParser({"at_user_list":[],"from_wxid":"wxid_4wkls7tu62ua12","is_pc":1,"msg":"dong","msgid":"7864579085001411733","room_wxid":"17962906510@chatroom","timestamp":1586403583,"to_wxid":"17962906510@chatroom","wx_type":1})
11:39:43 VERB Room ready()
11:39:43 VERB IoClient onMessage(Message#Text[🗣Contact<Friday BOT>@👥Room<ChatOps - CTP Status>]        dong)
11:39:43 VERB PuppetServiceImpl messagePayload()
11:39:43 VERB Puppet messagePayload(7864579085001411733)
11:40:43 VERB PuppetServiceImpl stop()
11:40:43 VERB EventStreamManager stop()
11:40:43 VERB EventStreamManager this.onStreamingCallEnd() this.eventStream.on(finish) fired
11:40:43 VERB EventStreamManager connectPuppetEventToStreamingCall() unconnect() 13 callbacks
11:40:43 VERB PuppetWindows stop()
11:40:43 VERB StateSwitch <PuppetDonut> off(pending) <- (false)
11:40:43 VERB PuppetWindows stopBridge()
11:40:43 VERB Bridge stop()
11:40:43 VERB CacheManager release()
11:40:43 VERB CacheManager releaseCache()
11:40:43 VERB StateSwitch <PuppetDonut> off(true) <- (pending)
11:40:43 WARN Io UNKNOWN on(online): puppet-hostie
11:40:43 WARN Io UNKNOWN on(offline): puppet-hostie
11:40:45 VERB PuppetServiceImpl start()
11:40:45 VERB PuppetWindows start()
11:40:45 VERB StateSwitch <PuppetDonut> on(pending) <- (false)
11:40:45 VERB PuppetWindows startBridge()
11:40:45 VERB Bridge start()
11:40:45 VERB Bridge getConnectCallback()
11:40:45 VERB Bridge getCloseCallback()
11:40:45 VERB Bridge getEventCallback()
11:40:45 VERB Donut(ffi-adapter) InitWeChatSocket(?(O,??O,??O)
11:40:45 VERB ffi-adapter Backend.lib(0: "C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dlls\WxLoader.dll")
11:40:45 VERB PuppetServiceImpl event()
11:40:45 VERB EventStreamManager start([object Object])
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() for Puppet#0<PuppetDonut>(donut-friday)
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(friendship) (listenerCount:1) registering...
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(login) (listenerCount:2) registering...
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(logout) (listenerCount:1) registering...
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(message) (listenerCount:1) registering...
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(room-invite) (listenerCount:1) registering...
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(room-join) (listenerCount:1) registering...
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(room-leave) (listenerCount:1) registering...
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(room-topic) (listenerCount:1) registering...
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(scan) (listenerCount:2) registering...
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(dong) (listenerCount:1) registering...
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(error) (listenerCount:1) registering...
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(heartbeat) (listenerCount:2) registering...
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(ready) (listenerCount:1) registering...
11:40:45 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(reset) (listenerCount:1) registering...
11:40:45 VERB EventStreamManager onStreamingCallEnd()
11:40:45 VERB EventStreamManager start() puppet is logged in, emit a login event for downstream
11:40:45 VERB Puppet selfId()
11:40:45 VERB EventStreamManager grpcEmit(EVENT_TYPE_LOGIN[25], {"contactId":"wxid_4wkls7tu62ua12"})
11:40:45 VERB Donut(ffi-adapter) InjectWeChat(C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dlls\WeChatHelper.dll)
11:40:45 VERB ffi-adapter Backend.lib(0: "C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dlls\WxLoader.dll")
11:40:45 VERB StateSwitch <PuppetDonut> on(true) <- (pending)
11:40:45 VERB Bridge processEvent(RECV_TEXT_MSG)
11:40:45 VERB PuppetWindows onMessage({"at_user_list":[],"from_wxid":"wxid_0mp2uchkzsx122","is_pc":0,"msg":"💪 (OSS Bot,OSS Bot)","msgid":"6795612989522998377","room_wxid":"17376996519@chatroom","timestamp":1586403644,"to_wxid":"17376996519@chatroom","wx_type":1})
11:40:45 VERB PuppetWindows contactRawPayload(wxid_0mp2uchkzsx122)
11:40:45 VERB Bridge contactRawPayload(wxid_0mp2uchkzsx122)
11:40:45 ERR Config ###########################
11:40:45 ERR Config unhandledRejection: Error: CacheManager getContact() has no cache. [object Promise]
11:40:45 ERR Config ###########################
11:40:45 ERR Config process.on(unhandledRejection) promise.catch(CacheManager getContact() has no cache.)
Config Error: CacheManager getContact() has no cache.
    at CacheManager.<anonymous> (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\src\donut\cache-manager.ts:76:13)
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\donut\cache-manager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\donut\cache-manager.js:4:12)
    at CacheManager.getContact (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\donut\cache-manager.js:63:16)
    at Bridge.<anonymous> (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\src\donut\bridge.ts:672:46)
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\donut\bridge.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\donut\bridge.js:4:12)
    at Bridge.contactRawPayload (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\donut\bridge.js:603:16)
    at PuppetDonut.<anonymous> (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\src\puppet-donut.ts:623:24)
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\puppet-donut.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\puppet-donut.js:4:12)
    at PuppetDonut.contactRawPayload (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\puppet-donut.js:503:16)
    at PuppetDonut.<anonymous> (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\src\puppet-donut.ts:276:18)
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\puppet-donut.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\puppet-donut.js:4:12)
    at PuppetDonut.onMessage (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\puppet-donut.js:196:16)
    at Bridge.emit (events.js:198:13)
    at Bridge.EventEmitter.emit (domain.js:448:20)
    at Bridge.<anonymous> (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\src\donut\bridge.ts:392:14)
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\donut\bridge.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\donut\bridge.js:4:12)
    at Bridge.processEvent (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\donut\bridge.js:229:16)
    at Bridge.<anonymous> (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\src\donut\bridge.ts:266:18)
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\donut\bridge.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\donut\bridge.js:4:12)
    at Bridge.onEvent (C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dist\src\donut\bridge.js:185:16)
    at C:\Users\Administrator\Desktop\testPuppetWindows\wechaty\node_modules\ffi\lib\callback.js:66:25

**Comment by su-chang** [comment]
Donut will release cache in `stop()` method, and restart without login event from WeChat, so cacheManager will not init.

And then it will cause this bug. `CacheManager getContact() has no cache. `

**Comment by huan** [comment]
Could you please check that whether the puppet can pass the "three start() then stop()" test? Like I send in the PR at <https://github.com/wechaty/wechaty-puppet-padplus/pull/190>

```ts
    for (let i = 0; i < 3; i++) {
      await puppet.start()
      await puppet.stop()
      t.pass('start/stop-ed at #' + i)
    }
    t.pass('PuppetPadplus() start/restart successed.')
```

If not, please make it pass this test so that the Puppet can be able to be managed by the Framework, then let's see if that could be helpful for this issue.

BTW: We can quote the log message into ``` for better readability.

**Comment by su-chang** [comment]
In donut, it could pass the "start() then stop() for three times" test.

**Comment by huan** [comment]
Great to know that! 

It would be great if we can add this test to the module to make sure it can always work as expected.
