### ISSUE TITLE
ERR StarterBot Error: no endpoint

### ISSUE THREAD

**Issue by dchaofei** [wechaty/wechaty-puppet-hostie#28]
Does wechaty-puppet-hostie need a specific token? I use padplus token to log in to wechaty-puppet-hostie prompt no endpoint.

```bash
15:04:55 INFO Wechaty <wechaty-puppet-hostie>(ding-dong-bot) start() v0.38.4 is starting...
15:04:56 ERR PuppetHostie start() rejection: no endpoint
Error: no endpoint
    at PuppetHostie.<anonymous> (/Users/dingchaofei/work/wechaty-getting-started/node_modules/wechaty/node_modules/wechaty-puppet-hostie/src/client/puppet-hostie.ts:215:15)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dingchaofei/work/wechaty-getting-started/node_modules/wechaty/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
15:04:56 ERR Wechaty start() exception: no endpoint
15:04:56 ERR StarterBot Error: no endpoint

```

**Comment by huan** [comment]
Yes, it needs a hostie token before it can be started.

You can apply one from https://github.com/wechaty/wechaty/issues/1941

**Comment by huan** [comment]
And also, you can host a hostie and create the token by yourself.

However, that would be a little bit complicated and we still have no documentation for it at all.

Please feel free to ask me about it at our meeting tomorrow if you want to have a try.
