### ISSUE TITLE
PuppetHostie start() rejection: no endpoint

### ISSUE THREAD

**Issue by windmemory** [wechaty/wechaty-puppet-hostie#39]
Today we've met two cases that the `wechaty-puppet-hostie` can not connect to the server. Here is the log:

```shell
11:57:37 INFO Listening on port 44971
11:57:37 INFO Connected to stream blender.
11:57:39 ERR PuppetHostie start() rejection: no endpoint
Error: no endpoint
    at PuppetHostie.<anonymous> (/xiaoju-bot/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:82:27)
    at Generator.next (<anonymous>)
    at fulfilled (/xiaoju-bot/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
11:57:39 ERR Wechaty start() exception: no endpoint
11:57:39 ERR errorListener Error happened:
Error: no endpoint
    at PuppetHostie.<anonymous> (/xiaoju-bot/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:82:27)
    at Generator.next (<anonymous>)
    at fulfilled (/xiaoju-bot/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
11:57:39 WARN PuppetHostie stop() is called on a OFF puppet. await ready(off) and return.
```

**Comment by huan** [comment]
This error message means that your hostie service is not online.

We can inspect a hostie service by our restful API: `api.chatie.io/v0/hosties/your_token`. If it shows `0.0.0.0` then we can confirm that the puppet service is not online for your token.

**Comment by su-chang** [comment]
Same error log:
```
09:54:30 INFO Listening on port 41199
09:54:30 INFO Connected to stream blender.
09:54:32 ERR PuppetHostie start() rejection: no endpoint
Error: no endpoint
    at PuppetHostie.<anonymous> (/xiaoju-bot/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:82:27)
    at Generator.next (<anonymous>)
    at fulfilled (/xiaoju-bot/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
09:54:32 ERR Wechaty start() exception: no endpoint
09:54:32 ERR errorListener Error happened:
Error: no endpoint
    at PuppetHostie.<anonymous> (/xiaoju-bot/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:82:27)
    at Generator.next (<anonymous>)
    at fulfilled (/xiaoju-bot/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
09:54:32 WARN PuppetHostie stop() is called on a OFF puppet. await ready(off) and return.
```

But we can get IP by API `api.chatie.io/v0/hosties/your_token`.

**Comment by su-chang** [comment]
When the io-client restart, and try `PuppetHostie start()` again, everything work nice.

**Comment by su-chang** [comment]
```
15:20:56 INFO Listening on port 43479
15:20:56 INFO Connected to stream blender.
15:21:13 ERR PuppetHostie start() rejection: Client network socket disconnected before secure TLS connection was established
{ Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1086:19)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET',
  path: undefined,
  host: 'api.chatie.io',
  port: 443,
  localAddress: undefined }
15:21:13 ERR Wechaty start() exception: Client network socket disconnected before secure TLS connection was established
15:21:13 ERR errorListener Error happened:
Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1086:19)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
15:21:13 WARN PuppetHostie stop() is called on a OFF puppet. await ready(off) and return.
```

**Comment by su-chang** [comment]
I have collected minimal reproduced log for `Error: no endpoint`.

@huan could you find something base this log?

## wechaty log and juzi log
```
13:54:21 INFO Listening on port 37137
13:54:21 INFO Connected to stream blender.
13:54:23 ERR PuppetHostie start() rejection: no endpoint
Error: no endpoint
    at PuppetHostie.<anonymous> (/xiaoju-bot/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:84:31)
    at Generator.next (<anonymous>)
    at fulfilled (/xiaoju-bot/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
13:54:23 ERR Wechaty start() exception: no endpoint
13:54:23 ERR errorListener Error happened:
Error: no endpoint
    at PuppetHostie.<anonymous> (/xiaoju-bot/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:84:31)
    at Generator.next (<anonymous>)
    at fulfilled (/xiaoju-bot/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
13:54:23 WARN PuppetHostie stop() is called on a OFF puppet. await ready(off) and return.

  ____        _      ___
 | __ )  ___ | |_   / _ \ _ __ __ _ _ __   __ _  ___
 |  _ \ / _ \| __| | | | | '__/ _` | '_ \ / _` |/ _ \
 | |_) | (_) | |_  | |_| | | | (_| | | | | (_| |  __/
 |____/ \___/ \__|  \___/|_|  \__,_|_| |_|\__, |\___|
                                          |___/
____________________________________________________
          https://www.botorange.com

Starting Docker Container for Xiaoju Bot with Node.js v10.15.0 ...
Working directory: /xiaoju-bot
Executing node index.js
14:04:54 SILL Config XIAOJU_LOG set level to silly
14:04:54 INFO Config registering process.on("unhandledRejection") for development/debug
14:04:55 INFO Environment Variables:
14:04:55 INFO ID: 5cd4dbbf454e8b4cc7b4c496
14:04:55 INFO BOT_IP: 52.81.33.64
14:04:55 INFO
```

## io-client log and donut log
```
13:54:09 VERB PuppetServiceImpl stop()
13:54:09 VERB EventStreamManager stop()
13:54:09 VERB PuppetDonut stop()
13:54:09 SILL StateSwitch <PuppetDonut> off() is false
13:54:09 SILL StateSwitch <PuppetDonut> off() is false
13:54:09 VERB StateSwitch <PuppetDonut> off(pending) <- (false)
13:54:09 VERB PuppetDonut stopBridge()
13:54:09 SILL StateSwitch <PuppetDonut> on() is false
13:54:09 VERB Bridge stop()
13:54:09 VERB CacheManager release()
13:54:09 VERB CacheManager releaseCache()
13:54:09 SILL CacheManager releaseCache() closing caches ...
13:54:09 SILL StateSwitch <Io> on() is true
13:54:09 VERB Io reconnect()
13:54:09 SILL StateSwitch <Io> off() is false
13:54:09 VERB Bridge processEvent(UNREAD_MSG_COUNT_CHANGE_MSG)
13:54:09 SILL Bridge syncRoomMember(17550370761@chatroom)
13:54:09 SILL request(DATA_CHATROOM_MEMBERS_MSG, [object Object]) 
13:54:09 VERB Donut(ffi-adapter) SendWeChatData(1,{"data":{"room_wxid":"17550370761@chatroom"},"type":11032})
13:54:09 VERB ffi-adapter Backend.lib(0: "C:\Users\Administrator\Desktop\testPuppetDonut\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dlls\WxLoader.dll")
13:54:09 SILL Bridge syncRoomMember(18650270803@chatroom)
13:54:09 SILL request(DATA_CHATROOM_MEMBERS_MSG, [object Object]) 
13:54:09 VERB Donut(ffi-adapter) SendWeChatData(1,{"data":{"room_wxid":"18650270803@chatroom"},"type":11032})
13:54:09 VERB ffi-adapter Backend.lib(0: "C:\Users\Administrator\Desktop\testPuppetDonut\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dlls\WxLoader.dll")
13:54:09 SILL Bridge syncRoomMember(18660770753@chatroom)
13:54:09 SILL request(DATA_CHATROOM_MEMBERS_MSG, [object Object]) 
13:54:09 VERB Donut(ffi-adapter) SendWeChatData(1,{"data":{"room_wxid":"18660770753@chatroom"},"type":11032})
13:54:09 VERB ffi-adapter Backend.lib(0: "C:\Users\Administrator\Desktop\testPuppetDonut\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dlls\WxLoader.dll")
13:54:09 SILL Bridge syncRoomMember(18021170756@chatroom)
13:54:09 SILL request(DATA_CHATROOM_MEMBERS_MSG, [object Object]) 
13:54:09 VERB Donut(ffi-adapter) SendWeChatData(1,{"data":{"room_wxid":"18021170756@chatroom"},"type":11032})
13:54:09 VERB ffi-adapter Backend.lib(0: "C:\Users\Administrator\Desktop\testPuppetDonut\wechaty\node_modules\@juzibot\wechaty-puppet-donut\dlls\WxLoader.dll")
13:54:09 VERB EventStreamManager this.onStreamingCallEnd() this.eventStream.on(cancelled) fired with arguments: {}
13:54:09 VERB EventStreamManager this.onStreamingCallEnd() this.eventStream.on(error) fired: Error: The async function encountered an error
13:54:09 VERB Io initWebSocket()
13:54:09 VERB Bridge processEvent(UNREAD_MSG_COUNT_CHANGE_MSG)
13:54:09 VERB Bridge processEvent(TRAYICON_SHOW_WINDOW_MSG)
13:54:09 SILL CacheManager releaseCache() cache closed.
13:54:09 SILL StateSwitch <PuppetDonut> off() is pending
13:54:09 VERB StateSwitch <PuppetDonut> off(true) <- (pending)
13:54:09 VERB Bridge processEvent(RECV_TEXT_MSG)
13:54:09 VERB BridgeCallback processMessage(RECV_TEXT_MSG)
13:54:09 SILL StatusMonitor statusMonitor()
13:54:09 VERB Bridge processEvent(UNREAD_MSG_COUNT_CHANGE_MSG)
13:54:09 VERB Bridge processEvent(TALKER_CHANGE_MSG)
13:54:09 VERB BridgeCallback processSyncData(TALKER_CHANGE_MSG, {"status":1,"user":{"avatar":"http://wx.qlogo.cn/mmcrhead/et9q9FvjBBrN8hYShibPBS1v5WDibIlPn4iadkACsJqqlbvSV0GXbIYne2aCdqAia1yicMa9XuuCoicIyXHkMwgae1aIPEGKj0gficQ/0","is_manager":0,"manager_wxid":"wxid_o5nhkj5drh4r12","nickname":"售后组常蕊-报警监测群","total_member":9,"wxid":"23803151513@chatroom"},"user_type":2})
13:54:09 SILL BridgeCallback processTalkerChange()
13:54:09 VERB Bridge processEvent(UNREAD_MSG_COUNT_CHANGE_MSG)
13:54:14 VERB Io initWebSocket() connected with protocol [io|0.0.1|cka63holw0000fksjfzqm9qaz]
13:54:14 SILL Io send({"name":"sys","payload":"Wechaty version 0.0.0 with CUID: cka63holw0000fksjfzqm9qaz"})
13:54:14 SILL Io initWebSocket() ws.on(message): {"name":"sys","payload":"registered"}
13:54:14 SILL Io initWebSocket() ws.on(message): {"name":"sys","payload":"roger"}
13:54:19 SILL Io start() setInterval() ws.ping()
13:54:24 VERB Bridge processEvent(TRAYICON_SHOW_WINDOW_MSG)
13:54:29 SILL Io start() setInterval() ws.ping()
13:54:39 SILL Io start() setInterval() ws.ping()
13:54:49 SILL Io start() setInterval() ws.ping()
13:54:59 SILL Io start() setInterval() ws.ping()
13:55:09 SILL Io start() setInterval() ws.ping()
13:55:19 SILL Io start() setInterval() ws.ping()
13:55:29 SILL Io start() setInterval() ws.ping()
13:55:39 SILL Io start() setInterval() ws.ping()
13:55:49 SILL Io start() setInterval() ws.ping()
13:55:59 SILL Io start() setInterval() ws.ping()
13:56:09 SILL Io start() setInterval() ws.ping()
13:56:19 SILL Io start() setInterval() ws.ping()
13:56:29 SILL Io start() setInterval() ws.ping()
13:56:39 SILL Io start() setInterval() ws.ping()
13:56:49 SILL Io start() setInterval() ws.ping()
13:56:59 SILL Io start() setInterval() ws.ping()
13:57:09 SILL Io start() setInterval() ws.ping()
13:57:19 SILL Io start() setInterval() ws.ping()
13:57:29 SILL Io start() setInterval() ws.ping()
13:57:39 SILL Io start() setInterval() ws.ping()
13:57:49 SILL Io start() setInterval() ws.ping()
13:57:59 SILL Io start() setInterval() ws.ping()
13:58:09 SILL Io start() setInterval() ws.ping()
13:58:19 SILL Io start() setInterval() ws.ping()
13:58:29 SILL Io start() setInterval() ws.ping()
13:58:39 SILL Io start() setInterval() ws.ping()
13:58:49 SILL Io start() setInterval() ws.ping()
13:58:59 SILL Io start() setInterval() ws.ping()
13:59:09 SILL Io start() setInterval() ws.ping()
13:59:19 SILL Io start() setInterval() ws.ping()
13:59:29 SILL Io start() setInterval() ws.ping()
13:59:39 SILL Io start() setInterval() ws.ping()
13:59:49 SILL Io start() setInterval() ws.ping()
13:59:59 SILL Io start() setInterval() ws.ping()
14:00:05 VERB Bridge processEvent(UNREAD_MSG_COUNT_CHANGE_MSG)
14:01:35 SILL Io start() setInterval() ws.ping()
14:01:35 SILL StateSwitch <Io> on() is true
14:01:35 VERB Io reconnect()
14:01:35 SILL StateSwitch <Io> off() is false
14:01:35 VERB Io initWebSocket()
14:01:36 VERB Io initWebSocket() connected with protocol [io|0.0.1|cka63holw0000fksjfzqm9qaz]
14:01:36 SILL Io send({"name":"sys","payload":"Wechaty version 0.0.0 with CUID: cka63holw0000fksjfzqm9qaz"})
14:01:36 SILL Io initWebSocket() ws.on(message): {"name":"sys","payload":"registered"}
14:01:37 SILL Io initWebSocket() ws.on(message): {"name":"sys","payload":"roger"}
14:01:45 SILL Io start() setInterval() ws.ping()
14:01:55 SILL Io start() setInterval() ws.ping()
14:02:05 SILL Io start() setInterval() ws.ping()
14:02:15 SILL Io start() setInterval() ws.ping()
14:02:25 SILL Io start() setInterval() ws.ping()
14:02:35 SILL Io start() setInterval() ws.ping()
14:02:45 SILL Io start() setInterval() ws.ping()
14:02:55 SILL Io start() setInterval() ws.ping()
14:03:05 SILL Io start() setInterval() ws.ping()
14:03:15 SILL Io start() setInterval() ws.ping()
14:03:25 SILL Io start() setInterval() ws.ping()
14:03:35 SILL Io start() setInterval() ws.ping()
14:03:45 SILL Io start() setInterval() ws.ping()
14:03:55 SILL Io start() setInterval() ws.ping()
14:04:05 SILL Io start() setInterval() ws.ping()
14:04:15 SILL Io start() setInterval() ws.ping()
14:04:25 SILL Io start() setInterval() ws.ping()
14:04:35 SILL Io start() setInterval() ws.ping()
14:04:45 SILL Io start() setInterval() ws.ping()
14:04:46 SILL Io initWebSocket() ws.on(message): {"name":"online","payload":"puppet-hostie"}
14:04:49 VERB PuppetServiceImpl start()
14:04:49 VERB PuppetDonut start()
```

**Comment by huan** [comment]
We can inspect a hostie service by visiting our restful API at: `api.chatie.io/v0/hosties/your_token`. If it shows `0.0.0.0` then we can confirm that the puppet service is not online for your token.

What do you get when you use the above API to get the IP of your token, does it shows your IP as expected?

**Comment by su-chang** [comment]
Yes, it shows the IP as expected.

**Comment by huan** [comment]
If the IP can be able to be displayed right, then we should not get the no endpoint error, because the endpoint is right there.

I'd like to have a look for you, if you can provide a minimum reproduce code snip for me. Or it will be better if you can setup a CodeSandbox environment to show it.

**Comment by windmemory** [comment]
Let's close this issue since we have reconnect logic to cover no endpoint problem.
