### ISSUE TITLE
io-client stop with unknow reason

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet-hostie#40]
Want to get your help for this problem, do you have some idea about this case? I will show some related logs here. Thank you very much.

**Clue**: the log file is more than 1GB in 5 hours.

**Log**
```
npm ERR! wechaty@0.39.29 io-client: `ts-node bin/io-client "heroku" "logs" "log"`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the wechaty@0.39.29 io-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-05-11T14_34_24_696Z-debug.log
```

**2020-05-11T14_34_24_696Z-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'io-client',
1 verbose cli   'heroku',
1 verbose cli   'logs',
1 verbose cli   '-t',
1 verbose cli   'log' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'preio-client', 'io-client', 'postio-client' ]
5 info lifecycle wechaty@0.39.29~preio-client: wechaty@0.39.29
6 info lifecycle wechaty@0.39.29~io-client: wechaty@0.39.29
7 verbose lifecycle wechaty@0.39.29~io-client: unsafe-perm in lifecycle true
8 verbose lifecycle wechaty@0.39.29~io-client: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Administrator\Desktop\testPuppetDonut\wechaty\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Program Files (x86)\nodejs\;C:\Program Files\Git\cmd;C:\Users\Administrator\.windows-build-tools\python27\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle wechaty@0.39.29~io-client: CWD: C:\Users\Administrator\Desktop\testPuppetDonut\wechaty
10 silly lifecycle wechaty@0.39.29~io-client: Args: [ '/d /s /c', 'ts-node bin/io-client "heroku" "logs" "log"' ]
11 silly lifecycle wechaty@0.39.29~io-client: Returned: code: 134  signal: null
12 info lifecycle wechaty@0.39.29~io-client: Failed to exec io-client script
13 verbose stack Error: wechaty@0.39.29 io-client: `ts-node bin/io-client "heroku" "logs" "log"`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid wechaty@0.39.29
15 verbose cwd C:\Users\Administrator\Desktop\testPuppetDonut\wechaty
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "io-client" "heroku" "logs" "-t" "log"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 134
22 error wechaty@0.39.29 io-client: `ts-node bin/io-client "heroku" "logs" "log"`
22 error Exit status 134
23 error Failed at the wechaty@0.39.29 io-client script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]
```

**Comment by huan** [comment]
Sorry but I have no idea about it because I can not understand what happened.
