### ISSUE TITLE
Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (4861442 vs. 4194304)

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet-hostie#41]
**Bot Receive a File Message**
```ts
await message.toFileBox()
```

**In `wechaty-puppet-donut`**
```ts
messageFile() {
  ...
  const fileBox = FileBox.fromFile(path, fileName)
  return FileBox.fromBase64(await fileBox.toBase64(), fileName)
}
```

**The Error Log**
```
Config { Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (4861442 vs. 4194304)
    at Object.exports.createStatusError (/Users/suchang/Desktop/PROJECT/Test/testDonut/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/suchang/Desktop/PROJECT/Test/testDonut/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/suchang/Desktop/PROJECT/Test/testDonut/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/suchang/Desktop/PROJECT/Test/testDonut/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/suchang/Desktop/PROJECT/Test/testDonut/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 8,
  metadata:
   Metadata {
     _internal_repr: { 'grpc-status': [Array], 'grpc-message': [Array] },
     flags: 0 },
  details: 'Received message larger than max (4861442 vs. 4194304)' }
```

**Related Code**
```ts
messageFile: async (call, callback) => {
  log.verbose('PuppetServiceImpl', 'messageFile()')

  try {
    const id = call.request.getId()

    const fileBox = await puppet.messageFile(id)

    const response = new MessageFileResponse()
    response.setFilebox(JSON.stringify(fileBox))

    return callback(null, response)

  } catch (e) {
    return grpcError('messageFile', e, callback)
  }
},
```

Related issue: https://github.com/huan/file-box/issues/25

**Comment by huan** [comment]
4194304  is 4MB, which is the GRPC default limitation for the protobuf data size.

According to https://stackoverflow.com/a/56768255/1123955, we can increase this limitation to 100MB by:

```
{
  "grpc.max_receive_message_length": 1024 * 1024 * 100,
  "grpc.max_send_message_length": 1024 * 1024 * 100,
}
```

However, I believe we should choice a size limitation first.

Do you have any propursal for this number?

**Comment by su-chang** [comment]
The rule of WeChat for send file require the file size less than 100Mb.

In consideration of the file convert to base64 it's size would be lager than itself. I think 120Mb is enough.

**Comment by huan** [comment]
I'd like to give more buffer to the limitation, let's use 150MB instead.

Could you please send a PR to increase it to 150MB? We need to modify both the client the server options.

**Comment by su-chang** [comment]
Agree!

With pleasure.

**Comment by su-chang** [comment]
This bug has been fixed and test just now, it should be closed.
