### ISSUE TITLE
Error: 2 UNKNOWN: Stream removed

### ISSUE THREAD

**Issue by archywillhe** [wechaty/wechaty-puppet-hostie#54]
Here is the last few lines of logs. 
```
message: {"_events":{},"_eventsCount":0,"id":"8750110666592211461","payload":{"filename":"","fromId":"wxid_d03nhnfu54pa12","id":"8750110666592211461","mentionIdList":[],"roomId":"","text":"I GOT THE. Gov money so i can trnfg","timestamp":1596289340000,"toId":"wxid_s27n2bzu71612","type":7}}
check
I GOT THE. Gov money so i can trnfg Message {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: '8750110666592211461',
  payload: {
    filename: '',
    fromId: 'wxid_d03nhnfu54pa12',
    id: '8750110666592211461',
    mentionIdList: [],
    roomId: '',
    text: 'I GOT THE. Gov money so i can trnfg',
    timestamp: 1596289340000,
    toId: 'wxid_s27n2bzu71612',
    type: 7
  },
  [Symbol(kCapture)]: false,
  [Symbol(name)]: 'Message',
  [Symbol(counter)]: 1772
}
message: {"_events":{},"_eventsCount":0,"id":"408865040613571269","payload":{"filename":"","fromId":"wxid_d03nhnfu54pa12","id":"408865040613571269","mentionIdList":[],"roomId":"","text":"U","timestamp":1596289342000,"toId":"wxid_s27n2bzu71612","type":7}}
check
U Message {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: '408865040613571269',
  payload: {
    filename: '',
    fromId: 'wxid_d03nhnfu54pa12',
    id: '408865040613571269',
    mentionIdList: [],
    roomId: '',
    text: 'U',
    timestamp: 1596289342000,
    toId: 'wxid_s27n2bzu71612',
    type: 7
  },
  [Symbol(kCapture)]: false,
  [Symbol(name)]: 'Message',
  [Symbol(counter)]: 1773
}
```
It was still working on 1st August 9:42pm. I was chatting with a friend. My bot was doing the logging. Nothing unusual was logged. 

![IMG_4235](https://user-images.githubusercontent.com/10269911/89154636-d183a680-d599-11ea-88dd-9e0e456577bf.JPG)

But at 9:51pm I got the `Stream removed` error while the bot was still running. And then my hostie server stopped working since then. I didn't receive any logs about needing to re-sign-in, or anything. Everything just stopped (though my server was still running with me still signed into hostie).

Did something happen to the grpc server?

```
ERR PuppetHostie stop() this.grpcClient.stop() rejection: 14 UNAVAILABLE: failed to connect to all addresses
ERR PuppetHostie start() rejection: no endpoint
WARN Puppet reset() exception: Error: no endpoint
Error: 
    at PuppetHostie.<anonymous> (/home/git/live/donut-test-ground/node_modules/wechaty/src/wechaty.ts:678:32)
    at PuppetHostie.emit (events.js:321:20)
    at PuppetHostie.EventEmitter.emit (domain.js:485:12)
    at PuppetHostie.emit (/home/git/live/donut-test-ground/node_modules/wechaty-puppet/src/puppet.ts:307:18)
    at /home/git/live/donut-test-ground/node_modules/wechaty-puppet/src/puppet.ts:434:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: 2 UNKNOWN: Stream removed
    at Object.exports.createStatusError (/home/git/live/donut-test-ground/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/git/live/donut-test-ground/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/git/live/donut-test-ground/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/git/live/donut-test-ground/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/git/live/donut-test-ground/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 2,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'Stream removed'
}
````

**Comment by archywillhe** [comment]
moved to https://github.com/juzibot/donut-tester/issues/36
