### ISSUE TITLE
wechaty-puppet-hostie stuck when connection to grpc throws error

### ISSUE THREAD

**Issue by windmemory** [wechaty/wechaty-puppet-hostie#73]
Scenario:

- Server started and reported the ip and port to api.chatie.io
- Client try to connect the server with the the ip and port
- Grpc server is not ready so client got a grpc server connection error
- client stuck, and will never try to connect the server anymore.

**Comment by lijiarui** [comment]
```
➜  wxwork-badcase git:(master) ✗ WECHATY_LOG=verbose ts-node wxwork.ts


13:50:31 INFO Config registering process.on("unhandledRejection") for development/debug
13:50:31 VERB Config constructor()
13:50:33 VERB Wechaty constructor()
13:50:33 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
13:50:33 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
13:50:33 VERB Wechaty on(scan, listener) registering... listenerCount: 0
13:50:33 VERB Wechaty on(login, listener) registering... listenerCount: 0
13:50:33 VERB Wechaty on(message, listener) registering... listenerCount: 0
13:50:33 VERB Wechaty <wechaty-puppet-hostie>() start() v0.47.24 is starting...
13:50:33 VERB Wechaty id: ckfaomd7e0000uyvsdn6kcidw
13:50:33 VERB StateSwitch <WechatyReady> off(true) <- (true)
13:50:33 VERB StateSwitch <Wechaty> on(pending) <- (false)
13:50:33 VERB MemoryCard constructor(undefined)
13:50:33 VERB MemoryCard getStorage() for storage type: N/A
13:50:33 VERB MemoryCard load() from storage: N/A
13:50:33 VERB MemoryCard load() no storage
13:50:33 VERB Wechaty initPuppet() wechaty-puppet-hostie
13:50:33 VERB MemoryCard multiplex(puppet)
13:50:33 VERB MemoryCard static multiplex(MemoryCard<>, puppet)
13:50:33 VERB MemoryCard constructor({"multiplex":{"name":"puppet","parent":{"payload":{},"multiplexNameList":[]}}})
13:50:33 VERB PuppetManager resolve({puppet: wechaty-puppet-hostie, puppetOptions: {"token":"puppet_wxwork_78e1c6d4fe4a0dc2"}})
13:50:33 VERB PuppetManager resolveName(wechaty-puppet-hostie)
13:50:33 VERB PuppetManager checkModule(wechaty-puppet-hostie)
13:50:33 VERB Puppet constructor({"token":"puppet_wxwork_78e1c6d4fe4a0dc2"}) #0
13:50:33 VERB StateSwitch constructor(PuppetHostie, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
13:50:33 VERB MemoryCard constructor(undefined)
13:50:33 VERB MemoryCard getStorage() for storage type: N/A
13:50:33 VERB MemoryCard load() from storage: N/A
13:50:33 VERB MemoryCard load() no storage
13:50:33 VERB Puppet constructor() watchdog timeout set to 60 seconds
13:50:33 VERB HotImport callerResolve(., /Users/jiaruili/git/wxwork-badcase/node_modules/wechaty-puppet/dist/src/puppet.js)
13:50:33 VERB Puppet constructor() childClassPath=/Users/jiaruili/git/wxwork-badcase/node_modules/wechaty-puppet-hostie/dist/src/client
13:50:33 VERB Puppet constructor() memory.load() done
13:50:33 VERB Puppet setMemory()
13:50:33 VERB Wechaty initPuppetEventBridge(Puppet#0<PuppetHostie>())
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(friendship) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(login) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(logout) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(message) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(room-invite) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(room-join) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(room-leave) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(room-topic) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(scan) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(dirty) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(dong) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(error) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(heartbeat) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(ready) (listenerCount:0) registering...
13:50:33 VERB Wechaty initPuppetEventBridge() puppet.on(reset) (listenerCount:0) registering...
13:50:33 VERB Wechaty wechatifyUserModules(Puppet#0<PuppetHostie>())
13:50:33 VERB PuppetHostie start()
13:50:33 VERB StateSwitch <PuppetHostie> on(pending) <- (false)
13:50:33 VERB PuppetHostie startGrpcClient()
13:50:33 VERB PuppetHostie discoverHostieIp(puppet_wxwork_78e1c6d4fe4a0dc2)
13:50:34 VERB PuppetHostie startGrpcStream()
13:50:34 VERB StateSwitch <PuppetHostie> on(true) <- (pending)
13:50:34 VERB Wechaty on(heartbeat, listener) registering... listenerCount: 0
13:50:34 VERB StateSwitch <Wechaty> on(true) <- (pending)



13:50:47 VERB PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]","timeout":60000}"})
13:51:17 VERB PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]","timeout":60000}"})
13:51:47 VERB PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]","timeout":60000}"})
```

**Comment by lijiarui** [comment]
```

14:09:05 VERB PuppetHostie discoverHostieIp(puppet_wxwork_cf9a5fba65c0ea81)
14:09:06 VERB PuppetHostie startGrpcStream()
14:09:08 ERR PuppetHostie start() rejection: 2 UNKNOWN: Stream removed
14:09:08 VERB StateSwitch <PuppetHostie> off(true) <- (false)
14:09:08 WARN Puppet reset() exception: Error: 2 UNKNOWN: Stream removed
14:09:08 ERR Config ###########################
14:09:08 ERR Config unhandledRejection: Error:
    at PuppetHostie.<anonymous> (/Users/jiaruili/git/wxwork-badcase/node_modules/wechaty/src/wechaty.ts:440:32)
    at PuppetHostie.emit (events.js:310:20)
    at PuppetHostie.EventEmitter.emit (domain.js:482:12)
    at /Users/jiaruili/git/wxwork-badcase/node_modules/wechaty-puppet/src/puppet.ts:324:14 [object Promise]
14:09:08 ERR Config ###########################
14:09:08 ERR Config process.on(unhandledRejection) promise.catch()
Config Error:
    at PuppetHostie.<anonymous> (/Users/jiaruili/git/wxwork-badcase/node_modules/wechaty/src/wechaty.ts:440:32)
    at PuppetHostie.emit (events.js:310:20)
    at PuppetHostie.EventEmitter.emit (domain.js:482:12)
    at /Users/jiaruili/git/wxwork-badcase/node_modules/wechaty-puppet/src/puppet.ts:324:14
(node:38849) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
14:09:08 VERB PuppetHostie startGrpcStream() eventStream.on(error) Error: 2 UNKNOWN: Stream removed
14:09:08 VERB Puppet reset(startGrpcStream() eventStream.on(error) Error: 2 UNKNOWN: Stream removed)
14:09:08
```

**Comment by windmemory** [comment]
```ts
// src/client/puppet-hostie.ts L262-L297
    try {
      await this.startGrpcClient()
      if (!this.grpcClient) {
        log.warn('PuppetHostie', 'start() failed to start grpc client, resetting self...')
        this.emit('reset', { data: 'failed to connect grpc client' })
        return
      }

      this.startGrpcStream()
      // this.startDing()

      await util.promisify(
        this.grpcClient.start
          .bind(this.grpcClient)
      )(new StartRequest())

      this.state.on(true)

      this.recoverSubscription = recover$(this).subscribe(
        x => log.verbose('PuppetHostie', 'constructor() recover$().subscribe() next(%s)', JSON.stringify(x)),
        e => log.error('PuppetHostie', 'constructor() recover$().subscribe() error(%s)', e),
        () => log.verbose('PuppetHostie', 'constructor() recover$().subscribe() complete()'),
      )

    } catch (e) {
      log.error('PuppetHostie', 'start() rejection: %s', e && e.message)

      if (this.grpcClient) {
        this.grpcClient.close()
        this.grpcClient = undefined
      }

      this.state.off(true)
      throw e

    }
```

From the code block above, if the `this.startGrpcStream()` or `this.grpcClient.start()` throws exception, the client will be stopped which will result in `wechaty-puppet-hostie` hangs there.

Similar to log: https://github.com/wechaty/wechaty-puppet-hostie/issues/74#issue-705054207

**Comment by windmemory** [comment]
After carefully reading the code in `wechaty-puppet-hostie` server, I found that this should be a bug resulting a race condition will potentially cause the client stuck.

Here is the code to start the `io-client`:

```ts
  public async start (): Promise<void> {
    log.verbose('IoClient', 'start()')

    if (this.state.on()) {
      log.warn('IoClient', 'start() with a on state, wait and return')
      await this.state.ready('on')
      return
    }

    this.state.on('pending')

    try {
      await this.hookWechaty(this.options.wechaty)

      await this.startIo()

      await this.options.wechaty.start()

      await this.startHostie()

      this.state.on(true)

    } catch (e) {
      log.error('IoClient', 'start() exception: %s', e.message)
      this.state.off(true)
      throw e
    }
  }
```

From the code block above, we know that we are launching the `io` first, then we launch the `wechaty`, finally we launch the `hostieServer`. And in the code to start `io`, we can see that:

```ts
  private async startIo (): Promise<void> {
    log.verbose('IoClient', 'startIo() with token %s', this.options.token)

    if (this.state.off()) {
      const e = new Error('startIo() state.off() is true, skipped')
      log.warn('IoClient', e.message)
      throw e
    }

    if (this.io) {
      throw new Error('io exists')
    }

    this.io = new Io({
      hostiePort : this.options.port,
      token      : this.options.token,
      wechaty    : this.options.wechaty,
    })

    try {
      await this.io.start()
    } catch (e) {
      log.verbose('IoClient', 'startIo() init fail: %s', e.message)
      throw e
    }
  }
```

The `io` will report the port and token to the server, then the server will know the client's ip and port to connect with, but at the moment that the server knows the ip and port, the hostie server has not been launched yet. If the client connect to the server at this time, there will be definitely an error thrown. And we didn't handle the error carefully, so this will result the client to be stuck.
