### ISSUE TITLE
[Bug] 崩溃以后黑屏不重启,GRPC Hostie bug 

### ISSUE THREAD

**Issue by windmemory** [wechaty/wechaty-puppet-hostie#74]
puppet 版本： 0.1.65

上线以后稳定崩溃，崩溃以后黑屏，黑屏后无法自动把进程启动，卡死。

novnc 界面

![image](https://user-images.githubusercontent.com/6419514/93704968-cbe31f80-fb4b-11ea-87f6-e1469b47c311.png)

grpc 崩溃日志：

```
14:07:49 VERB PuppetHostie startGrpcStream() eventStream.on(error) Error: 2 UNKNOWN: Stream removed
14:07:49 VERB Puppet reset(startGrpcStream() eventStream.on(error) Error: 2 UNKNOWN: Stream removed)
14:07:49 VERB PuppetHostie stop()
14:07:49 VERB StateSwitch <PuppetHostie> off(pending) <- (false)
14:07:49 VERB PuppetHostie stopGrpcStream()
14:07:49 VERB PuppetHostie stopGrpcClient()
14:07:49 VERB StateSwitch <PuppetHostie> off(true) <- (pending)
14:07:49 VERB PuppetHostie start()
14:07:49 VERB StateSwitch <PuppetHostie> on(pending) <- (false)
14:07:49 VERB PuppetHostie startGrpcClient()
14:07:49 VERB PuppetHostie discoverHostieIp(puppet_wxwork_cf9a5fba65c0ea81)
14:07:51 VERB PuppetHostie startGrpcStream()
14:07:51 VERB StateSwitch <PuppetHostie> on(true) <- (pending)
14:07:52 VERB PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]","timeout":60000}"})
14:08:32 VERB PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]","timeout":60000}"})
14:08:53 VERB PuppetHostie startGrpcStream() eventStream.on(error) Error: 2 UNKNOWN: Stream removed
14:08:53 VERB Puppet reset(startGrpcStream() eventStream.on(error) Error: 2 UNKNOWN: Stream removed)
14:08:53 VERB PuppetHostie stop()
14:08:53 VERB StateSwitch <PuppetHostie> off(pending) <- (false)
14:08:53 VERB PuppetHostie stopGrpcStream()
14:08:54 ERR PuppetHostie stop() stop GRPC rejection: 2 UNKNOWN: Stream removed
14:08:54 VERB StateSwitch <PuppetHostie> off(true) <- (pending)
14:08:54 VERB PuppetHostie start()
14:08:54 VERB StateSwitch <PuppetHostie> on(pending) <- (false)
14:08:54 VERB PuppetHostie startGrpcClient()
14:08:54 VERB PuppetHostie discoverHostieIp(puppet_wxwork_cf9a5fba65c0ea81)
14:08:55 WARN No endpoint when starting grpc client, 10 retry left. Reconnecting in 10 seconds...


14:09:05 VERB PuppetHostie discoverHostieIp(puppet_wxwork_cf9a5fba65c0ea81)
14:09:06 VERB PuppetHostie startGrpcStream()
14:09:08 ERR PuppetHostie start() rejection: 2 UNKNOWN: Stream removed
14:09:08 VERB StateSwitch <PuppetHostie> off(true) <- (false)
14:09:08 WARN Puppet reset() exception: Error: 2 UNKNOWN: Stream removed
14:09:08 ERR Config ###########################
14:09:08 ERR Config unhandledRejection: Error:
    at PuppetHostie.<anonymous> (/Users/jiaruili/git/wxwork-badcase/node_modules/wechaty/src/wechaty.ts:440:32)
    at PuppetHostie.emit (events.js:310:20)
    at PuppetHostie.EventEmitter.emit (domain.js:482:12)
    at /Users/jiaruili/git/wxwork-badcase/node_modules/wechaty-puppet/src/puppet.ts:324:14 [object Promise]
14:09:08 ERR Config ###########################
14:09:08 ERR Config process.on(unhandledRejection) promise.catch()
Config Error:
    at PuppetHostie.<anonymous> (/Users/jiaruili/git/wxwork-badcase/node_modules/wechaty/src/wechaty.ts:440:32)
    at PuppetHostie.emit (events.js:310:20)
    at PuppetHostie.EventEmitter.emit (domain.js:482:12)
    at /Users/jiaruili/git/wxwork-badcase/node_modules/wechaty-puppet/src/puppet.ts:324:14
(node:38849) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
14:09:08 VERB PuppetHostie startGrpcStream() eventStream.on(error) Error: 2 UNKNOWN: Stream removed
14:09:08 VERB Puppet reset(startGrpcStream() eventStream.on(error) Error: 2 UNKNOWN: Stream removed)
14:09:08 VERB PuppetHostie stop()
14:09:08 WARN PuppetHostie stop() is called on a OFF puppet. await ready(off) and return.
14:09:08 VERB StateSwitch <PuppetHostie> ready(off, false)
14:09:08 VERB PuppetHostie start()
14:09:08 VERB StateSwitch <PuppetHostie> on(pending) <- (false)
14:09:08 VERB PuppetHostie startGrpcClient()
14:09:08 VERB PuppetHostie discoverHostieIp(puppet_wxwork_cf9a5fba65c0ea81)
14:09:09 WARN No endpoint when starting grpc client, 10 retry left. Reconnecting in 10 seconds...
14:09:19 VERB PuppetHostie discoverHostieIp(puppet_wxwork_cf9a5fba65c0ea81)
14:09:20 WARN No endpoint when starting grpc client, 9 retry left. Reconnecting in 10 seconds...
14:09:30 VERB PuppetHostie discoverHostieIp(puppet_wxwork_cf9a5fba65c0ea81)
14:09:34 VERB PuppetHostie startGrpcStream()
14:09:34 ERR PuppetHostie start() rejection: event stream exists
14:09:34 VERB StateSwitch <PuppetHostie> off(true) <- (false)
14:09:34 WARN Puppet reset() exception: Error: event stream exists
14:09:34 ERR Config ###########################
14:09:34 ERR Config unhandledRejection: Error:
    at PuppetHostie.<anonymous> (/Users/jiaruili/git/wxwork-badcase/node_modules/wechaty/src/wechaty.ts:440:32)
    at PuppetHostie.emit (events.js:310:20)
    at PuppetHostie.EventEmitter.emit (domain.js:482:12)
    at /Users/jiaruili/git/wxwork-badcase/node_modules/wechaty-puppet/src/puppet.ts:324:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5) [object Promise]
14:09:34 ERR Config ###########################
14:09:34 ERR Config process.on(unhandledRejection) promise.catch()
Config Error:
    at PuppetHostie.<anonymous> (/Users/jiaruili/git/wxwork-badcase/node_modules/wechaty/src/wechaty.ts:440:32)
    at PuppetHostie.emit (events.js:310:20)
    at PuppetHostie.EventEmitter.emit (domain.js:482:12)
    at /Users/jiaruili/git/wxwork-badcase/node_modules/wechaty-puppet/src/puppet.ts:324:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:38849) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)

```

**Comment by lijiarui** [comment]
对应的server 端日志：

```
file: c:\data\devops\p-7d78c07a8051498aaabc190612411ad8\src\storage\common\sqlite\statement_impl.cpp
line number: 21
error: file is not a database
file: c:\data\devops\p-7d78c07a8051498aaabc190612411ad8\src\storage\common\sqlite\statement_impl.cpp
line number: 21
error:0072:fixme:wtsapi:WTSUnRegisterSessionNotification Stub 000100B4
 file is not a database
file: c:\data\devops\p-7d78c07a8051498aaabc190612411ad8\src\storage\common\sqli0072:fixme:win:UnregisterTouchWindow (0x100b4): stub
te\statement_impl.cpp
line number: 21
error: file is not a database
file: c:\data\devops\p-7d78c07a8051498aaabc190612411ad8\src\storage\common\sqlite\statement_impl.cpp
line number: 21
err14:31:26 VERB Bridge onEvent() type: 11027(MT_USER_LOGOUT), data: {"data":{"user_id":"1688850321476353"},"type":11027}
or14:31:26 VERB Manager processEvent() receive logout event: {"user_id":"1688850321476353"}
: 14:31:26 VERB BaseData getBotInfo(1688850321476353)
file i14:31:26 VERB BaseData setBotInfo(1688850321476353)
s not 14:31:26 VERB BaseData logout()
a 14:31:26 INFO PuppetWork onLogout(1688850321476353)
da14:31:26 VERB PuppetWork stop()
ta14:31:26 VERB StateSwitch <PuppetWork> off(pending) <- (false)
ba14:31:26 VERB PuppetWork stopManager()
se14:31:26 VERB Manager stop()

14:31:26 VERB Bridge stop()
14:31:26 VERB Work(ffi-adapter) DestroyWxWork()
14:31:26 VERB ffi-adapter Backend.lib(0: "Z:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\dlls\WxWorkLoaderJs.dll")
file: c:\data\devops\p-7d78c07a8051498aaabc190612411ad8\src\storage\common\sqlite\statement_impl.cpp
line number: 21
error: file is not a database
file: c:\data\devops\p-7d78c07a8051498aaabc190612411ad8\src\storage\common\sqlite\statement_impl.cpp
line number: 21
error: file is not a database
file:007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x83626e4,0x8303370): stub
 c:\data\devops\007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x83f12f4,0x8331108): stub
p-7d78c07a8051498007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x83f12f4,0x8331108): stub
0072:fixme:advapi:OpenEventLogW ((null),L"System") stub
0072:fixme:advapi:ReadEventLogA (0xcafe4242,0x00000009,0x00000000,0xf242bc8,0x00010000,0x32fa28,0x32fa24) stub
0072:fixme:advapi:CloseEventLog (0xcafe4242) stub
aa0072:fixme:netprofm:ConnectionPointContainer_FindConnectionPoint interface {dcb00004-570f-4a9b-8d69-199fdba5723b} not implemented
abc190072:fixme:netprofm:ConnectionPointContainer_FindConnectionPoint interface {dcb00004-570f-4a9b-8d69-199fdba5723b} not implemented
061007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dc5174,0x8331108): stub
2411ad8\src\storage\007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x18a8073c,0x82f6100): stub
common\sqlite\statement_impl.cpp
line number: 21
error: file is not007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de4334,0x82f6100): stub
 a database
file: c:\da007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x82e0034,0x82f6100): stub
ta\devops\p-7d78c07a007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5def6e4,0x82f6100): stub
8051498aaabc190612411ad8\sr007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dee834,0x82f6100): stub
c\storage\common007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5def6e4,0x82f6100): stub
\sqlite\statement_impl.cpp
line number: 21
error: file is007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x18a8073c,0x82f6100): stub
 not a database
file:007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x82e0034,0x82f6100): stub
 c:\data\devops\p-7d78c07a8051498aaabc190612411ad8\src007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de4334,0x82f6100): stub
\storage\common\sqlite\stat007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x18a8073c,0x82f6100): stub
ement_impl.cpp
line number:007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x82e0034,0x82f6100): stub
 21
error: file is not a da007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dee834,0x82f6100): stub
tabase
file: c:\data007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x82e0034,0x82f6100): stub
\devops\p-7d78c07a8051498aaabc190612411ad8\src\storage007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de4334,0x82f6100): stub
\common\sqlite\statement_im007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
pl.cpp
line number: 21
erro007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
r: file is not a database
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de4334,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de4334,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de4334,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de4334,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de64f4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de4334,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de64f4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de4334,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de4334,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de64f4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de64f4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de64f4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
0069:fixme:thread:NtQueryInformationThread Cannot get kerneltime or usertime of other threads
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
14:31:27 VERB Bridge stop() destroyWxWorkResult: true
14:31:27 VERB Manager releaseQueue()
14:31:27 VERB BaseData release()
14:31:27 VERB CacheManager release()
14:31:27 VERB CacheManager releaseCache()
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
14:31:27 VERB Manager stop() stopped
14:31:27 VERB StateSwitch <PuppetWork> off(true) <- (pending)
14:31:27 VERB PuppetWork stop() stopped
14:31:27 VERB EventStreamManager grpcEmit(EVENT_TYPE_LOGOUT[26], {"contactId":"1688850321476353","data":"logout"})
14:31:27 VERB ContactSelf name()
14:31:27 INFO IoClient 李佳芮 logged out
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dbdac4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dee834,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dbdac4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dee834,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dbdac4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x8388d3c,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dee834,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dc05bc,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dc05bc,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dee834,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dc05bc,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5dc05bc,0x82f6100): stub
007b:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x5de72b4,0x82f6100): stub
0072:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0162:fixme:wtsapi:WTSUnRegisterSessionNotification Stub 000200F0
0072:fixme:msvcrt:__clean_type_info_names_internal (0x5bc73a4) stub
0072:fixme:msvcrt:__clean_type_info_names_internal (0x5b6d424) stub
0072:fixme:msvcrt:__clean_type_info_names_internal (0x3d7980) stub
0162:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0162:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0032FEAC
```

**Comment by huan** [comment]
Close this issue because I do not think the puppet system has any relationship to "黑屏"
