### ISSUE TITLE
Wechaty start() exception: discoverHostieIp() timeout to get any ip info from all hostie endpoints.

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty-puppet-hostie#75]
```
➜  wxwork-badcase git:(master) WECHATY_LOG=verbose ts-node wxwork.ts
18:52:15 INFO Config registering process.on("unhandledRejection") for development/debug
18:52:15 VERB Config constructor()
18:52:16 VERB Wechaty constructor()
18:52:16 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
18:52:16 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
18:52:16 VERB Wechaty on(scan, listener) registering... listenerCount: 0
18:52:16 VERB Wechaty on(login, listener) registering... listenerCount: 0
18:52:16 VERB Wechaty on(message, listener) registering... listenerCount: 0
18:52:16 VERB Wechaty <wechaty-puppet-hostie>() start() v0.47.24 is starting...
18:52:16 VERB Wechaty id: ckfazedm70000jvfyeqpr32pi
18:52:16 VERB StateSwitch <WechatyReady> off(true) <- (true)
18:52:16 VERB StateSwitch <Wechaty> on(pending) <- (false)
18:52:16 VERB MemoryCard constructor(undefined)
18:52:16 VERB MemoryCard getStorage() for storage type: N/A
18:52:16 VERB MemoryCard load() from storage: N/A
18:52:16 VERB MemoryCard load() no storage
18:52:16 VERB Wechaty initPuppet() wechaty-puppet-hostie
18:52:16 VERB MemoryCard multiplex(puppet)
18:52:16 VERB MemoryCard static multiplex(MemoryCard<>, puppet)
18:52:16 VERB MemoryCard constructor({"multiplex":{"name":"puppet","parent":{"payload":{},"multiplexNameList":[]}}})
18:52:16 VERB PuppetManager resolve({puppet: wechaty-puppet-hostie, puppetOptions: {"token":"puppet_wxwork_416ccdaa2f11bd1b"}})
18:52:16 VERB PuppetManager resolveName(wechaty-puppet-hostie)
18:52:16 VERB PuppetManager checkModule(wechaty-puppet-hostie)
18:52:16 VERB Puppet constructor({"token":"puppet_wxwork_416ccdaa2f11bd1b"}) #0
18:52:16 VERB StateSwitch constructor(PuppetHostie, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
18:52:16 VERB MemoryCard constructor(undefined)
18:52:16 VERB MemoryCard getStorage() for storage type: N/A
18:52:16 VERB MemoryCard load() from storage: N/A
18:52:16 VERB MemoryCard load() no storage
18:52:16 VERB Puppet constructor() watchdog timeout set to 60 seconds
18:52:16 VERB HotImport callerResolve(., /Users/jiaruili/git/wxwork-badcase/node_modules/wechaty-puppet/dist/src/puppet.js)
18:52:16 VERB Puppet constructor() childClassPath=/Users/jiaruili/git/wxwork-badcase/node_modules/wechaty-puppet-hostie/dist/src/client
18:52:16 VERB Puppet constructor() memory.load() done
18:52:16 VERB Puppet setMemory()
18:52:16 VERB Wechaty initPuppetEventBridge(Puppet#0<PuppetHostie>())
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(friendship) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(login) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(logout) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(message) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(room-invite) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(room-join) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(room-leave) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(room-topic) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(scan) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(dirty) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(dong) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(error) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(heartbeat) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(ready) (listenerCount:0) registering...
18:52:16 VERB Wechaty initPuppetEventBridge() puppet.on(reset) (listenerCount:0) registering...
18:52:16 VERB Wechaty wechatifyUserModules(Puppet#0<PuppetHostie>())
18:52:16 VERB PuppetHostie start()
18:52:16 VERB StateSwitch <PuppetHostie> on(pending) <- (false)
18:52:16 VERB PuppetHostie startGrpcClient()
18:52:16 VERB PuppetHostie discoverHostieIp(puppet_wxwork_416ccdaa2f11bd1b)
undefined
18:52:21 ERR PuppetHostie start() rejection: discoverHostieIp() timeout to get any ip info from all hostie endpoints.
18:52:21 VERB StateSwitch <PuppetHostie> off(true) <- (false)
Error: discoverHostieIp() timeout to get any ip info from all hostie endpoints.
    at PuppetHostie.discoverHostieIp (/Users/jiaruili/git/wxwork-badcase/node_modules/wechaty-puppet-hostie/src/client/puppet-hostie.ts:176:13)
18:52:21 ERR Wechaty start() exception: discoverHostieIp() timeout to get any ip info from all hostie endpoints.
18:52:21 ERR Config ###########################
18:52:21 ERR Config unhandledRejection: Error: discoverHostieIp() timeout to get any ip info from all hostie endpoints.
    at PuppetHostie.discoverHostieIp (/Users/jiaruili/git/wxwork-badcase/node_modules/wechaty-puppet-hostie/src/client/puppet-hostie.ts:176:13) [object Promise]
18:52:21 ERR Config ###########################
18:52:21 ERR Config process.on(unhandledRejection) promise.catch(discoverHostieIp() timeout to get any ip info from all hostie endpoints.)
Config Error: discoverHostieIp() timeout to get any ip info from all hostie endpoints.
    at PuppetHostie.discoverHostieIp (/Users/jiaruili/git/wxwork-badcase/node_modules/wechaty-puppet-hostie/src/client/puppet-hostie.ts:176:13)
(node:44779) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

**Comment by lijiarui** [comment]
Seems due to the network...
