### ISSUE TITLE
wechaty-puppet-hostie say()报错

### ISSUE THREAD

**Issue by webweifeng** [wechaty/wechaty-puppet-hostie#96]
初始化方法：
const puppet = new Wechaty({
  name: '测试机器人',
  puppet: new PuppetHostie({ token: '', endpoint: '114.215.83.32:7777' }),
});

调用方法：
 puppet.say('你好！')

错误信息：
{ Error: 10 ABORTED: {"code":9999}
    at Object.exports.createStatusError (/Users/front/DEV/website/test/node_modules/_grpc@1.24.3@grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/front/DEV/website/test/node_modules/_grpc@1.24.3@grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/front/DEV/website/test/node_modules/_grpc@1.24.3@grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/front/DEV/website/test/node_modules/_grpc@1.24.3@grpc/src/client_interceptors.js:618:8)
    at callback (/Users/front/DEV/website/test/node_modules/_grpc@1.24.3@grpc/src/client_interceptors.js:847:24)
  code: 10,
  metadata:
   Metadata {
     _internal_repr:
      { 'grpc-accept-encoding': [Array], 'accept-encoding': [Array] },
     flags: 0 },
  details: '{"code":9999}' }

**Comment by huan** [comment]
It seems that you are not connected to your Wechaty puppet service provider right.

I'd like to suggest that you can contact your wechaty puppet service provider (who gives you the token) for troubleshooting.
